import type { CapacitorConfig } from '@capacitor/cli';

/**
 * Capacitor Configuration - ACTIVE (auto-managed)
 * 
 * This file is auto-generated by the mode switch scripts.
 * Don't edit directly - use the scripts instead:
 * 
 * - npm run ios:dev  → local dev server + test keys
 * - npm run ios:prod → hosted HTTPS + live keys
 * 
 * See capacitor.config.dev.ts and capacitor.config.prod.ts for templates.
 */

const config: CapacitorConfig = {
  appId: 'com.shiftx.customer',
  appName: 'ShiftX Customer (Dev)',
  webDir: '../customer-app/dist',
  server: {
    url: 'http://127.0.0.1:5173',
    cleartext: true,
  },
  ios: {
    contentInset: 'automatic',
  }
};

export default config;
