// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi9fz_lpRJh1dEnmRekGVh3Jc9JAyYHnU',
    appId: '1:928827778230:web:ac7b78dcf4d7b93d22f217',
    messagingSenderId: '928827778230',
    projectId: 'shiftx-95c4b',
    authDomain: 'shiftx-95c4b.firebaseapp.com',
    storageBucket: 'shiftx-95c4b.firebasestorage.app',
    measurementId: 'G-7KZ2KN26WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFf0ild8hOCn0rulXgytENqljtw198S7Q',
    appId: '1:928827778230:android:bbd7bd69aa4b7f1a22f217',
    messagingSenderId: '928827778230',
    projectId: 'shiftx-95c4b',
    storageBucket: 'shiftx-95c4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO0QMKEC8_ry0aClOnvN1UaBFWSgVCGLI',
    appId: '1:928827778230:ios:410ba15c05aa06dd22f217',
    messagingSenderId: '928827778230',
    projectId: 'shiftx-95c4b',
    storageBucket: 'shiftx-95c4b.firebasestorage.app',
    iosBundleId: 'com.example.shiftx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO0QMKEC8_ry0aClOnvN1UaBFWSgVCGLI',
    appId: '1:928827778230:ios:410ba15c05aa06dd22f217',
    messagingSenderId: '928827778230',
    projectId: 'shiftx-95c4b',
    storageBucket: 'shiftx-95c4b.firebasestorage.app',
    iosBundleId: 'com.example.shiftx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi9fz_lpRJh1dEnmRekGVh3Jc9JAyYHnU',
    appId: '1:928827778230:web:7de93c3e107f9bec22f217',
    messagingSenderId: '928827778230',
    projectId: 'shiftx-95c4b',
    authDomain: 'shiftx-95c4b.firebaseapp.com',
    storageBucket: 'shiftx-95c4b.firebasestorage.app',
    measurementId: 'G-ML9D0P4M0N',
  );
}
